baseURL = 'https://classicbaseball.world/'
languageCode = 'en-us'
title = 'Classic Baseball World'
theme = 'PaperMod'
publishDir = "docs"

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  description = "The Criterion Collection of the Diamond. A complete archive of baseball cinema."

[services]
  [services.googleAnalytics]
    id = "" 

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5